# Menu Configuration for the Alpha Theme
# This file defines menu entries for the site's default language.
#
# Menus supported:
#   - main
#   - main_secondary
#   - main_social
#   - footer
#   - footer_social
#   - sc_social
#
# For multilingual setups, create equivalent files using the language code.
# Example: `menus.fr.toml` for the French version.
#
# Documentation:
# - Menus: https://alpha.oxypteros.com/docs/config/menus-toml/
# - Multilingual: https://alpha.oxypteros.com/docs/multilingual/
# - Shortcodes: https://alpha.oxypteros.com/docs/shortcodes/social/

# Main Menu
[[main]]        
  name = "Home"
  url = "/"
  weight = 100

[[main]]
  name = "Meat Hacker"
  url = "/meathacker/"
  weight = 100

[[main]]
  name = "Rivergraph"
  url = "/rivergraph/"
  weight = 100

# Main Secondary
#[[main_secondary]]
#  name = "About Me"
#  url = "/about/"
#  weight = 100

# Main Social
[[main_social]]
  name = "Mastodon"
  url = "http://c.im/@dtauvdiodr"
  pre = "#mastodon"
  weight = 100

# Footer Menu
#[[footer]]
#  name = "Policy"
#  url = "/policy/"
#  weight = 100

# Footer Social
#[[footer_social]]
#  name = "X"
#  url = "https://x.com/your-username"
#  pre = "#twitter" # Renders a specific icon. See docs for available icons.
#  weight = 100

# Shortcode Social
[[sc_social]]
  name = "Mastodon"
  url = "http://c.im/@dtauvdiodr"
  pre = "#mastodon"
  weight = 100